### ISSUE TITLE
Logs showing timestamps in UTC (not local time)

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#114]
Following up: https://community.home-assistant.io/t/having-trouble-with-appdaemon-and-sunsets/24272/23

When I run `date` on my Raspberry Pi, I get the correct local time:

```
Mon 14 Aug 20:42:19 MDT 2017
```

When I run `date` inside my AppDaemon Docker container, I still get the correct time (albeit in slightly different format):

```
Mon Aug 14 20:42:51 MDT 2017
```

When I restart that container, the Docker logs (which are simply outputting the AppDaemon logs directly) show something very different:

```
2017-08-15 02:43:46.279341 INFO Loading Object...
```

Since I'm in MDT, that timestamp is in UTC.

**Comment by acockburn** [comment]
Looking into this - I have a couple of questions:

1. What timezone do you have set in Home Assistant
2. Have you tried using the AppDaemon timezone directive to explicitly set the timezone?

Looking at the code, AppDaemon gets the TZ normally from HASS, but you can override it.

**Comment by bachya** [comment]
Thank you!

I'm using `America/Denver` in HASS. When I _don't_ use the `time_zone` directive in AppDaemon:

```
AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  # various key/value pairs
```

...the logs show UTC time:

```
2017-08-15 19:14:24.031478 INFO Got initial state
2017-08-15 19:14:24.035315 INFO Loading Module...
```

When I _do_ use the `time_zone` directive in AppDaemon:

```
AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  # various key/value pairs
  time_zone: America/Denver
```

...the logs still show UTC time:

```
2017-08-15 19:15:04.031478 INFO Got initial state
2017-08-15 19:15:04.035315 INFO Loading Module...
```
