### ISSUE TITLE
Using scandic characters (å, ä, ö...) doesn't work

### ISSUE THREAD

**Issue by JoniR** [home-assistant/appdaemon#118]
Using scandic characters for sensor title like ä and ö in HADashboard is preventing Dashboard to load.
Example 
```
utility_humidity:
    widget_type: sensor
    title: Lämmönjakohuone
    units: "%"
    precision: 0
    entity: sensor.utility_room_humidity
```
Log says:
`WARNING Error opening dashboard file '/home/homeassistant/.homeassistant/conf/dashboards/Home.dash'`

If I remove ä or ö from title, then this will work

**Comment by acockburn** [comment]
What happens if you use quotes?

**Comment by JoniR** [comment]
Awesome! Now I can pull HADashboard in to the "production" since this was last excuse by wife to not seen texts as local language. Using quotes solve this issue:
```
utility_humidity:
    widget_type: sensor
    title: "Lämmönjakohuone"
    units: "%"
    precision: 0
    entity: sensor.utility_room_humidity
```
