### ISSUE TITLE
Sunset automation runs multiple times

### ISSUE THREAD

**Issue by bachya** [home-assistant/appdaemon#129]
I have the following app to turn on lights 30 minutes before sunset (this is in `lights.py`):

```Python
import appdaemon.appapi as appapi


class EveningLights(appapi.AppDaemon):
    """Define a class to represent the app."""

    def initialize(self):
        """Initialize."""
        self.run_at_sunset(self.sunset_cb, offset=-60 * 30)

    def sunset_cb(self, kwargs):
        """Turn on the living room lights just before sunset."""
        self.log('30 minutes before sunset triggered; turning on lights')
        self.turn_on('group.living_room_lights')
```
The app ran tonight, but according to the logs, it seemed to run three times:

```
2017-08-26 19:10:09.020369 INFO evening_lights: 30 minutes before sunset triggered; turning on lights
2017-08-26 19:18:14.024341 INFO evening_lights: 30 minutes before sunset triggered; turning on lights
2017-08-26 19:34:07.026033 INFO evening_lights: 30 minutes before sunset triggered; turning on lights
```

Not sure why?

**Comment by acockburn** [comment]
IS there anything else in the logs? Can I see the whole log from startup please?

**Comment by bachya** [comment]
@acockburn: You got it: as soon as it runs this evening, I'll send along. Thanks!

**Comment by acockburn** [comment]
OK, are you setting a timezone in your config? I just saw something that might be related to this.

**Comment by bachya** [comment]
I'm not. Here's my non-app-specific config:

```
AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  api_port: 5051
  api_key: <APPDAEMON API KEY>
HASS:
  ha_url: <HOME ASSISTANT URL>
  ha_key: <HOME ASSISTANT KEY>
```
