### ISSUE TITLE
Password Protect HADashboard Issue

### ISSUE THREAD

**Issue by BigHomie90** [home-assistant/appdaemon#1376]
Hello, i am trying to password protect ha dashboard. I am running App Daemon 4 (0.7.0) Home assistant addon.
Here is my appdaemon config.

```
secrets: /config/secrets.yaml
appdaemon:
  latitude: 52.379189
  longitude: 4.899431
  elevation: 2
  time_zone: Europe/Athens
  plugins:
    HASS:
      type: hass
http:
  url: http://127.0.0.1:5050
  password: testpassword
admin:
api:
hadashboard:

```
Web interface now asks for a password but when i log in all my entities are missing so when i load the dashboard i can see only the names of the tiles etc.

App daemon log errors: 

2021-10-22 13:05:40.449071 INFO AppDaemon: App initialization complete
2021-10-22 13:06:08.897525 INFO AppDaemon: Successful logon from 192.168.1.30:5050
2021-10-22 13:06:09.284590 WARNING AppDaemon: Unexpected error in JSON conversion when receiving from stream
2021-10-22 13:06:09.287861 INFO AppDaemon: Client disconnection from Admin Client
2021-10-22 13:06:10.298742 WARNING AppDaemon: Unexpected error in JSON conversion when receiving from stream
2021-10-22 13:06:10.299533 INFO AppDaemon: Client disconnection from Admin Client
2021-10-22 13:06:11.308311 WARNING AppDaemon: Unexpected error in JSON conversion when receiving from stream
2021-10-22 13:06:11.308985 INFO AppDaemon: Client disconnection from Admin Client
2021-10-22 13:06:12.998319 INFO AppDaemon: Compiling dashboard 'House10'
2021-10-22 13:06:14.008830 INFO AppDaemon: function [get_dashboard] finished in 1013 ms
2021-10-22 13:06:14.367759 WARNING AppDaemon: Unexpected error in JSON conversion when receiving from stream
2021-10-22 13:06:14.378881 INFO AppDaemon: Client disconnection from Main Panel
2021-10-22 13:06:15.612114 WARNING AppDaemon: Unexpected error in JSON conversion when receiving from stream
2021-10-22 13:06:15.612945 INFO AppDaemon: Client disconnection from Main Panel
2021-10-22 13:06:17.611704 WARNING AppDaemon: Unexpected error in JSON conversion when receiving from stream
2021-10-22 13:06:17.612799 INFO AppDaemon: Client disconnection from Main Panel

If i remove the password entry under http:  everything works fine except that dashboard is unprotected.

If anyone knows how to solve this, please help me.

Thank you!
