### ISSUE TITLE
Secrets in appdaemon.yaml get replaced with their cleartext value

### ISSUE THREAD

**Issue by pschmitt** [home-assistant/appdaemon#167]
I am using appdaemon via Docker and intended to use the following `appdaemon.yaml` file:

```yaml
AppDaemon:
  disable_apps: 1
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
HASS:
  ha_url: !secret ha_url
  ha_key: !secret ha_key
HADashboard:
  dash_url: !secret dash_url
```

... but each time I restart the container the `!secret` statements get replaced by their cleartext content ie. `ha_url: !secret MY_SECRET` turns into `ha_url: XXXXXXXXXX`
