### ISSUE TITLE
Image in iframe on dashboard does not refresh

### ISSUE THREAD

**Issue by marhoy** [home-assistant/appdaemon#181]
I have created a dashboard with a meteogram (weather forecast) inside an iframe. The image on the web-server is recreated every 10 minutes.

The image is displayed in the dashboard, but it is not refreshed automatically. I have to reload the dashboard in order to refresh the image. I've tested with Chrome and Safari.

I've tried different hacks, using img_list or url_list, and repeating the same url two times. No luck so far. Any idea what I am doing wrong? Is it a bug?

I'm running the latest hass.io installation (HA 0.60 and appdaemon add-on 0.3.0, the log reports AppDaemon Version 2.1.12) on an rpi3.

The relevant configuration-entries looks like this:

```
title: Gangen                
widget_dimensions: [128, 115]
widget_margins: [4, 4]                           
columns: 6                                       

meteogram:
  widget_type: iframe
  refresh: 60        
  img_list:          
    - http://www.pvv.ntnu.no/~gunde/meteogram.png

layout:                                          
  - clock, spacer, spacer, meteogram(3x2)        
```
