### ISSUE TITLE
Problem with ports while configuring HADashboard

### ISSUE THREAD

**Issue by yannick9906** [home-assistant/appdaemon#182]
My first configuration was Port 3030 set in Hass.io Interface and `dash_url: 'http://domain:3030'` which didn't work out. `http://domain:3030` refuses to connect.

Second try was to leave out the port in appdaemon.yaml and only using `dash_url: 'http://domain'` which was reachable, but every action or link leaves the port out too.

Also: How do you activate SSL, since you can't set https as dash_url.

Anything i did wrong while configuring?

appdaemon.yaml:
```yaml
AppDaemon:
  logfile: STDOUT
  errorfile: STDERR
  logsize: 100000
  log_generations: 3
  threads: 10
  disable_apps: 1
HASS:
  ha_url: https://domain:8123
  ha_key: ********

HADashboard:
  dash_url: 'http://domain'
  #dash_ssl_certificate: /ssl/fullchain.pem
  #dash_ssl_key: /ssl/privkey.pem
```
