### ISSUE TITLE
Time constraint throwing TypeError

### ISSUE THREAD

**Issue by jshank** [home-assistant/appdaemon#183]
Only seems to apply to constrain_end_time

apps.yaml

```
christsmas-tree:
 module: ChristmasTree
 class: ChristmasTree
 sensor: sensor.elk_zone_002
 tree_switch: switch.zw_012_onoff_power_switch
 sensor_trigger_state: Violated
 tree_on_minutes: 60
 constrain_start_time: 08:00:00
 constrain_end_time: 22:00:00
 constrain_presence: anyone
```
Log output
```
appdaemon_1  | 2017-12-21 11:51:19.499989 WARNING ------------------------------------------------------------
appdaemon_1  | 2017-12-21 11:51:19.500240 WARNING Unexpected error during process_message()
appdaemon_1  | 2017-12-21 11:51:19.500478 WARNING ------------------------------------------------------------
appdaemon_1  | 2017-12-21 11:51:19.502551 WARNING Traceback (most recent call last):
appdaemon_1  |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 763, in process_message
appdaemon_1  |     process_state_change(data)
appdaemon_1  |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 714, in process_state_change
appdaemon_1  |     callback["kwargs"]
appdaemon_1  |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 652, in check_and_disapatch
appdaemon_1  |     "kwargs": kwargs
appdaemon_1  |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 243, in dispatch_worker
appdaemon_1  |     if not check_time_constraint(conf.app_config[name], name):
appdaemon_1  |   File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 229, in check_time_constraint
appdaemon_1  |     if not utils.now_is_between(start_time, end_time, name):
appdaemon_1  |   File "/usr/local/lib/python3.6/site-packages/appdaemon/utils.py", line 246, in now_is_between
appdaemon_1  |     end_time = parse_time(end_time_str, name)
appdaemon_1  |   File "/usr/local/lib/python3.6/site-packages/appdaemon/utils.py", line 193, in parse_time
appdaemon_1  |     parts = re.search('^(\d+):(\d+):(\d+)', time_str)
appdaemon_1  |   File "/usr/local/lib/python3.6/re.py", line 182, in search
appdaemon_1  |     return _compile(pattern, flags).search(string)
appdaemon_1  | TypeError: expected string or bytes-like object
appdaemon_1  |
appdaemon_1  | 2017-12-21 11:51:19.502804 WARNING ------------------------------------------------------------

```
