### ISSUE TITLE
Javascript widget standard practices

### ISSUE THREAD

**Issue by cgarwood** [home-assistant/appdaemon#229]
The (undocumented) Javascript widget doesn't seem to follow the standard practices. There's the base widget files (in a `javascript` folder, whereas most other base widgets are in folders starting with `base`), and it is lacking the derived widget .yaml file that specifies defaults for the different widget variables. 

It still functions as long as you specify all of the variables in the dashboard file:
```
tablet_off:
    widget_type: javascript
    fields:
      title: Tablet Off
      title2: ""
      icon: "fa-tv"
    static_css:
      title_style: ""
      title2_style: ""
      icon_style: ""
      widget_style: ""
    icons:
      icon_active: "fa-tv"
      icon_inactive: "fa-tv"
    command: "fully.startScreensaver();"
```
