### ISSUE TITLE
"telegram_bot/send_message" Error

### ISSUE THREAD

**Issue by kaykoch** [home-assistant/appdaemon#2378]
### What happened?

AppDaemon
Aktuelle Version: 0.17.4 

Since a view weeks I cannot send telegram messages anymore.
this code works for more than 3 years:
```
    self.call_service(
        "telegram_bot/send_message",
        message=message,
        title=title,
        target=id
    )
    
    #    for example:
    self.call_service(
        "telegram_bot/send_message",
        title="*a title*",
        target=1234567,
        message="A message",
    )
```

Right now I got:
 **Error with websocket result: invalid_format: expected a dictionary for dictionary value @ data['target']. Got 1234567**

In an automation, this works:
```
actions:
  - action: telegram_bot.send_message
    data:
      title: "*a title*"
      target: "1234567"
      message: "A message"
```

Error is related to **target**
Any ideas?

sincerly
Kay

### Version

4.5.8

### Installation type

Home Assistant add-on

### Relevant log output

```sh
Error with websocket result: invalid_format: expected a dictionary for dictionary value @ data['target']. Got 1234567
```

### Relevant code in the app or config file that caused the issue

```sh
self.call_service(
        "telegram_bot/send_message",
        message=message,
        title=title,
        target=id
    )
```
