### ISSUE TITLE
Return to the main page

### ISSUE THREAD

**Issue by miraixyz** [home-assistant/appdaemon#242]
I am not sure if this issue has been raised yet,so sorry if this is a repeat.

I am using HADashboard, and have included the Navigate widget., with the return argument so
that the page returns back to the page that I specified.  The link works fine, but only if I don't press and other buttons on that page.  

If I press any buttons however, the browser will stay on that page and won't return to the specified page.

Not sure if any else is having this issue but I want to know if there is a workaround or fix for this.

my code:
```

return:
    widget_type: navigate
    title: Control Panel
    dashboard: Main
    args:
      skin: obsidian
      timeout: 15
      return: front
```
