### ISSUE TITLE
Setting sensor's value as widget title (or else) + as image url

### ISSUE THREAD

**Issue by MPopti0n** [home-assistant/appdaemon#261]
Running HADashboard/appdeamon3 on rasberryPi3 (Home assistant version `0.65.3`)

Hi, i'm building a dashboard to control a media player (Bose Soundtouch)

I'm trying to show the actual name of the preset on a script widget

Using MQTT/Mosquitto/Node-Red to extract those values from the xml api file ending up with a sensor.bosepreset1.....

The next block don't do nothing (the widget appear and is working but no text), is there a way to do that?

```
preset1:
    widget_type: script
    entity: script.bosepreset1
    sub_entity: sensor.bosepreset1
    icon_on: mdi-numeric-1-box
    icon_off: mdi-numeric-1-box-outline
    icon_style_inactive: "font-size: 1%; margin-top: -35px"
    icon_style_active: "font-size: 1%;margin-top: -35px"
```

SECOND THING

I'm trying to put the actual image of the playing station on the dashboard, no problem getting the url from the api but the value is stored in a sensor, how can I use that value as the url_list of an iframe widget?

The next return a error 500 showin in the widget on the actual dashboard : 

```
imagestation:
    widget_type: iframe
    url_list: '{{ states.sensor.BoseArt.state }}'
    refresh: 3
```

Yes I did google A LOT! 😄 in the past few day with no success!!
