### ISSUE TITLE
Temperature widget not updating as expected

### ISSUE THREAD

**Issue by cloggedDrain** [home-assistant/appdaemon#262]
I'm having an issue with the Temperature widget.  It displays the correct value of the sensor and does draw the range specified with the proper colors, but the red marks don't seem to move.

Example of the temperature widget rendered:
![image](https://user-images.githubusercontent.com/28632707/37597320-7dbbbe84-2b55-11e8-98be-fd50b500d8fd.png)

I've configured with widget with the following:
```
water_temp:
  widget_type: temperature
  entity: sensor.fishtank_water_temp
  settings:
    minValue: 70
    maxValue: 86
    width: 220
    height: 550
    majorTicks: [70,72,74,76,78,80,82,84,86]
    highlights: [{'from': 70, 'to': 76, 'color': 'rgba(0,0, 255, .3)'},{'from': 76, 'to': 79, 'color': 'rgba(37, 209, 69, .3)'},{'from': 79, 'to': 86, 'color': 'rgba(255, 0, 0, .3)'}]
```

The only way I've been able to get the red line to move is by changing minValue to 0:
![image](https://user-images.githubusercontent.com/28632707/37597411-c2352794-2b55-11e8-9575-375e2b1456a2.png)

I'm not sure why it's moving with minValue set to 0 and not when I specify a tighter range
