### ISSUE TITLE
Dashboard: 500 Error

### ISSUE THREAD

**Issue by lebaned** [home-assistant/appdaemon#274]
After the upgrade from 2.1.12 to 3.0.0 Appdaemon is working fine, but my dashboards give an 500 error.  It looks like the dashboards also not being compiled. The folders 'css' and 'javascript' be created but stay empty. For testing I've created a new dashboard with only a label element. 

My dashboard: 
```yaml
title: Test Panel
widget_dimensions: [120, 120]
widget_margins: [5, 5]
columns: 8

label:
  widget_type: label
  title: label
  title2: label 2
  text: Blaat
     
layout:
  label(3x1)
```
My appdaemon.yaml
```yaml
log:
  accessfile: /home/homeassistant/.appdaemon/logs/access.log
  errorfile: /home/homeassistant/.appdaemon/logs/error.log
  logfile: /home/homeassistant/.appdaemon/logs/appdaemon.log
  log_generations: 3
  log_size: 1024
appdaemon:
  threads: 15
  api_port: 5000
  api_key: [removed]
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.1.21:8123
      ha_key: [removed]
      namespace: default
      timeout: 60
hadashboard:
  dash_url: http://192.168.1.21:5050
  dash_force_compile: 1
  dash_compile_on_start: 1
```
