### ISSUE TITLE
Reopen of #167: Secrets in appdaemon.yaml get replaced with their cleartext value 

### ISSUE THREAD

**Issue by rtclauss** [home-assistant/appdaemon#280]
My new install of AppDaemon on Hass.io experiences the same problems as #167 where the my `!secret` statement sin `appdaemon.yaml` are replaced with new values for `ha_key`

```yaml
secrets: /config/secrets.yaml
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      ha_key: !secret ha_api key
...
```
becomes:
```yaml
secrets: /config/secrets.yaml
log:
  logfile: STDOUT
  errorfile: STDERR
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      ha_key: XXXXXXXXXXXXXXXXXXX
```
