### ISSUE TITLE
even in empty dashboard: error Widget definition not found

### ISSUE THREAD

**Issue by alexgeertsema** [home-assistant/appdaemon#290]
Using most recent Hass.io and Appdeamon 3 1.0.1

I saw the error uppon creating a dashboard.  
even with a complete empty dash  and only one spacer in the dash it states the not found error in a widget block.

if i fill widgets the error always is the last one at the right.
It happens only at the first row and if it runs out of space due to the widgets it 
overlaps the first one in the row.

My .dash file is like this:

```
##
## Main arguments, all optional
##
title: Home
widget_dimensions: [120, 120]
widget_size: [1, 1]
widget_margins: [5, 5]
columns: 5
global_parameters:
    use_comma: 0
    precision: 1
    use_hass_icon: 1

layout:
    - spacer,

```

Anyone give me a pointer where to look perhaps ? :)

Best regards,
Alex
