### ISSUE TITLE
Refresh of iframe doesn't work with a single URL in url_list

### ISSUE THREAD

**Issue by corrafig** [home-assistant/appdaemon#333]
I was trying to have a single cat URL in iframe widget that would be refreshed every 5th second.

**The refresh doesn't work when the widget is configured as below**
```
iframe_1:
    widget_type: iframe
    title: Cat pages
    refresh: 5
    url_list:
      - https://www.pexels.com/photo/grey-and-white-short-fur-cat-104827/
```

**My workaround was to duplicate the very same URL as a different string**
```
iframe_1:
    widget_type: iframe
    title: Cat pages
    refresh: 5
    url_list:
      - https://www.pexels.com/photo/grey-and-white-short-fur-cat-104827/
      - https://www.pexels.com/photo/grey-and-white-short-fur-cat-104827/?ignoreThis
```
I'm using `appdaemon` version 3.0.1. The refresh does work with a single URL when using `img_list` instead of `url_list`.
