### ISSUE TITLE
Multiple entities per widget

### ISSUE THREAD

**Issue by Drachenkaetzchen** [home-assistant/appdaemon#335]
From reading through the code of [basedisplay.js](appdaemon/widgets/basedisplay/basedisplay.js) it appears that there's some initial support for passing multiple entities per widget.

A use case, for example, would be a widget which displays the router's up- and downstream values. However, with my initial tests, I could not pass multiple entities to the widget.

Questions:
- Is this actually supported?
- If supported, is there any example?
- If unsupported or not yet supported, is there a way to make this work?

**Comment by MPopti0n** [comment]
I don't know if that's what you're looking for but you can ::

- Option A
Set a `sub_entity` in a `widget_type: sensor`

```
temp_hum:
    widget_type: sensor
    title: Température
    entity: sensor.netatmo_interieur_temperature
    value_style: "font-size: 500%; margin-top: -60px"
    unit_style: "margin-top: -60px"
    title2: Humidité
    sub_entity: sensor.netatmo_interieur_humidity
    title2_style: "margin-top: 80px"
    state_text_style: "font-size: 500%; color: blue"
```
Note that with that you can't set a `unit` for the `sub_entity`, but you can plat with the lines `title2_style` and `state_text_style` to format it as you want

- Option B (the easiest and the cleaner one in my opinion!)
Change your `widget_dimensions` to half of their size to create 2 `widget_type: sensor` that have the size of one

Option A on the left and B on the right
![dash](https://user-images.githubusercontent.com/36873863/42017352-a7908778-7a7c-11e8-9271-b73a9560781f.jpg)


***Complete basic code for that dashboard

```
title: dashboard

widget_dimensions: [100, 97]
widget_margins: [1, 1]
columns: 10

dash_url: http://127.0.0.1:5050/dashboard


temp_hum:
    widget_type: sensor
    title: Température
    entity: sensor.netatmo_interieur_temperature
    value_style: "font-size: 500%; margin-top: -60px"
    unit_style: "margin-top: -60px"
    title2: Humidité
    sub_entity: sensor.netatmo_interieur_humidity
    title2_style: "margin-top: 80px"
    state_text_style: "font-size: 500%; color: blue"

temp:
    widget_type: sensor
    title: Température
    entity: sensor.netatmo_interieur_temperature


hum:
    widget_type: sensor
    title: Humidité
    entity: sensor.netatmo_interieur_humidity
    
layout:
    -
    - temp_hum(2x2), temp(1x1)
    -                hum(1x1)
```
