### ISSUE TITLE
Climate Widget Units not displayed

### ISSUE THREAD

**Issue by borpin** [home-assistant/appdaemon#378]
The `units` element for the climate widget do not display.

I have look at the rendered CSS and it looks the same as the CSS for a temperature sensor widget but there is no text loaded.

[edit] The up and down icons are not correctly positioned in the 'box' so if the size in increased they do not center in the space available.

Sorry - no idea on CSS!

**Comment by ReneTode** [comment]
please tell us how you configured the widget.
and what size do you use for your widgets?

**Comment by borpin** [comment]
Not really changed much from the example (extract of full config). Just fiddling ATM seeing what is possible.  Same result no mater the sizing.
```yaml
title: Main Panel
widget_dimensions: [120, 120]
widget_size: [1, 1]
widget_margins: [5, 5]
columns: 8

inttemperature:
    widget_type: sensor
    entity: sensor.inttemperature
    title: Internal Temperature

climatecontrol:
    widget_type: climate  
    level_style: "font-size: 600%;"
    level2_style: "font-size: 300%;"
    unit_style: "font-size: 600%;"
    title_style: "font-size: 200%;"
    level_up_style: "font-size: 200%;"
    title: Family Room
    entity: climate.sunroom
    units: '°C'
    step: 0.1
    precision: 1

layout:
    - clock (3x1), inttemperature, sensor.speedtest
    - climatecontrol (2x2), switchstate, heatstate, int_temp_radial
    - reloadpage
```
CSS of climate units element - note no text loaded.
```css
<p class="unit" data-bind="html: unit, attr:{ style: unit_style}" style="color: #00aaff;font-size: 600%;"></p>
```
CSS of sensor units element.
```css
<p class="unit" data-bind="html: unit, attr:{ style: unit_style}" style="color: #00aaff;font-size: 100%;">°C</p>
```
Display - note the position of the '+' button.
![image](https://user-images.githubusercontent.com/1322749/46584492-d76ed600-ca5b-11e8-9b41-3b26e1b4a4c5.png)

**Comment by ReneTode** [comment]
i notice there is a small error in the docs.
you need to use unit and not units.

the other problem you did cause yourself by putting this in the widget:
```
    level_up_style: "font-size: 200%;"
```
you change the size from level up but not from level down.

i think its wise to look at the docs (there is no level2 so also no level2_syle) and when you want to start modifying things you need to learn some css, without it you cant change appearance. ;)

**Comment by ReneTode** [comment]
it isnt in the right place because you did change the size.
if you start to change CSS (which you do when you change size) you cant expect that all other css will change also.
so if you start changing sizes from elements, you probably also need to realine the elements.

and i was mistaken, there is a level2, but its left out in the docs.
i guess thats forgotten.
ill make a pr for that. (also for unit)

i dont use climate entities, so i cant try a climate widget myself ;) 

but its called uni in the yaml file and in the html file so i am 100% sure that you need to use unit

**Comment by borpin** [comment]
Working on the basis that the basedisplay works and the climate doesn't, I have looked for differences in how the units is set.  There are obvious differences.

I don't now if I am right - it is deduction on my part.

The basedisplay widget checks to see if there is anything in `units` otherwise looks it the source entity, but loads that in a different manner to the climate widget as it uses `state.attributes["unit_of_measurement"]`

https://github.com/home-assistant/appdaemon/blob/49414de5f7fdc20736a15eda7f9998e8bb431baf/appdaemon/widgets/basedisplay/basedisplay.js#L122-L133


https://github.com/home-assistant/appdaemon/blob/49414de5f7fdc20736a15eda7f9998e8bb431baf/appdaemon/widgets/baseclimate/baseclimate.js#L65-L72

**Comment by ReneTode** [comment]
you are right.
the climate takes the unit from HA.
so in the HA configuration a unit should be set. (if possible at all)

ill speak to Andrew if he wants to change that in the docs or in the code

**Comment by ReneTode** [comment]
i made a PR and when everything is right it will be added in the next release.

**Comment by borpin** [comment]
Note that the syntax is **not** correct for the climate widget to pull in the units.

**From the display widget (works)**

`self.set_field(self, "unit", state.attributes["unit_of_measurement"])`

**From the climate widget (doesn't work)**

`self.set_field(self, "unit", state.attributes.unit_of_measurement)`

**Comment by ReneTode** [comment]
both syntaxes are correct.
that part gets the state from the HA sensor not from the widget yaml

that it doesnt get the data from the widget settings is because this is missing

         self.set_field(self, "unit", self.parameters.units)

**Comment by borpin** [comment]
> both syntaxes are correct.
that part gets the state from the HA sensor not from the widget yaml

@ReneTode, I have no idea if the syntax (in theory) are both right or not, all I can say is the syntax in the `baseclimate` does not work, but the syntax in the `basedisplay` does when loading from the source entity i.e. there is no `units` or `unit` variable set.
```
climatecontrol:
    widget_type: climate  
    title: Family Room
    entity: climate.sunroom
    step: 0.1
    precision: 1
```
And just the temperature...
```
inttemperature:
    widget_type: sensor
    entity: sensor.inttemperature
    title: Internal Temperature
```

I'll try and clone this widget and create a new base widget.  Could you tell me the right location under `\config\appdaemon` please.  The documentation is not clear.
