### ISSUE TITLE
Dash_Password doesn't read from secrets.yaml

### ISSUE THREAD

**Issue by eugenelai** [home-assistant/appdaemon#415]
Noticed that dash_password doesn't use the password stored in secrets.yaml file anymore, it just uses the dash_password variable. E.g.

```
hadashboard:
  dash_url: https://xxx.duckdns.org:5050
  dash_dir: /config/appdaemon/dashboards
  dash_ssl_certificate: /ssl/fullchain.pem
  dash_ssl_key: /ssl/privkey.pem
  dash_password: !secret dash_password
```
The password to login to HADashboard is "dash_password" and not what is stored in the secrets.yaml file under dash_password
