### ISSUE TITLE
AppDaemon Adding Parameters To URL on Navigate Widget

### ISSUE THREAD

**Issue by JZ-SmartThings** [home-assistant/appdaemon#434]
I'm having an issue when using the config below. I'm trying to link to an external link but it errors out because AppDaemon adds **?skin=default** to the tail end of the URL and some things (like HA Camera Proxy) don't appreciate the extra parameter on the URL. Ideally, the parameter should only be passed if there's currently one in the URL or make it optional because you never know where externally somebody is going and whether the extra param breaks things. Secondly, it would be great if one could specify whether the window should open in a "_blank" new window/tab or take over the current window. Please see my example below and let me know if there are any questions. Thank you for this AMAZING add-on which makes every old tablet useful for HA!

```
load_amcrest_children:
    widget_type: navigate
    title: Amcrest Children
    icon: mdi-camera
    url: http://192.168.1.123:8123/api/camera_proxy/camera.amcrest_children?api_password=mylegacypassword
```

**Comment by JZ-SmartThings** [comment]
Yep, both of those options seem to work well especially when I use the camera_proxy devices type in HA in order to limit/customize the dimensions of the camera feed. I tried your way @ReneTode but the camera feed in that iframe was huge and had large scroll bars. Camera_proxy HA component (lets you specify image width) was a perfect workaround for that. So now I can indeed see all 4 cameras on a single AppDaemon dashboard and it looks great. I'm so damn close to the ideals I've had in my mind for years with this stuff.

@acockburn appreciate the consideration for ability to control the target tag in HTML. It'll be a much welcome enhancement.

I do have one left over problem (BTW, I am using your dev branch with the socksio and iPad 1 support and a few other ones like old 3.0.2 and the socksjs version from the community post --- all have the same result). Using the exact widget example you posted above and the icon definition, it still uses the fa-gear icon instead of the mdi-camera icon I define. Not sure how to fix that as I've tried many things. I do have these things in my yaml. As an FYI, the socksio version in the dev branch is not working while the socksjs docker image is updating devices as expected. On the community thread you mentioned to clean cache and recompile dashboards. I'll try Googling that but I did dump the appdaemon/compiled folder to no avail.

```
hadashboard:
  dash_url: http://192.168.1.123:5050
  dash_dir: /conf/dashboards
  transport: socketio
  fa4compatibility: 1
```

Appreciate the help very much gents!

**Comment by ReneTode** [comment]
> I tried your way @ReneTode but the camera feed in that iframe was huge and had large scroll bars

i was not talking about using an iframe.
my suggestion (which i use)
is to create a dashboard like:

```
title: camera
widget_dimensions: [100, 98]
widget_size: [1,1]
widget_margins: [2, 2]
columns: 10

layout:
    - my_camera(10x6)

my_camera:
    widget_type: camera
    entity_picture: http://ha_ip:8123/api/camera_proxy_stream/camera.hoofdterrascam?api_password=mypw
    title: hoofdterrascam
    refresh: 120
```
and navigate to that.
you wont get scrollbars at all.
