### ISSUE TITLE
Running hello world application uses 100% CPU and uses more and more memory (3.0.2@ubuntu 18.04)

### ISSUE THREAD

**Issue by matkor** [home-assistant/appdaemon#487]
Starting simple hello world app consumes 100% CPU and eats more and more memory.
I run it:
`python3 -m appdaemon.admain -c ./hello_world.conf`

hello_world.conf/appdaemon.yaml contains:
```
appdaemon:
  threads: 10
  plugins:
    HASS:
      type: hass
      ha_url: http://192.168.9.4:8123
      token:  REMOVED
```

hello_world.conf/apps/apps.yaml :
```
hello_world:
  module: hello
  class: HelloWorld

```

hello_world.conf/apps/hello.py :
```
import appdaemon.plugins.hass.hassapi as hass

#
# Hello World App
#
# Args:
#

class HelloWorld(hass.Hass):

  def initialize(self):
     self.log("Hello from AppDaemon")
     self.log("You are now ready to run Apps!")

```

**Comment by ReneTode** [comment]
what system do you run it on?
what version is appdaemon?
what is in the logs?
why is your config dir called hello_world.conf?
why do you start admain?

https://appdaemon.readthedocs.io/en/latest/INSTALL.html#running

**Comment by matkor** [comment]
> you installed appdaemon with pip3 in a venv called heatcontrol.venv with a conf dir called hello_world.conf inside the venv?

IIRC - yes.

> are you really trying to confuse yourself?

No. 

> what else is there in your config dir except
appdaemon.yaml
apps/hello.py
apps/apps.yaml
```
(heatcontol.venv) matkor@matkor-lenovo:~/src/appdaemon/heatcontol.venv$ tree hello_world.conf/
hello_world.conf/
├── appdaemon.yaml
└── apps
    ├── apps.yaml
    └── hello.py
```
> and did you restart your device before restarting appdaemon?

I run appdaemon on my laptop, and it was restarted at least once.

**Comment by matkor** [comment]
>better to set logfiles. it shows more because its the expected behaviour. (and only run debug if needed, lets try it without first)

Having added:
```
appdaemon:
  log_thread_actions: 1

log:
  logfile: appdaemon.log
  errorfile: error.log
  diagfile: diag.log

```

I get nothing more than in console:

matkor@matkor-lenovo:~/src/appdaemon/heatcontol.venv$ tail -f *.log
==> appdaemon.log <==
```
2019-01-21 16:10:59.040758 INFO AppDaemon Version 3.0.2 starting
2019-01-21 16:10:59.041095 INFO Configuration read from: ./hello_world.conf/appdaemon.yaml
2019-01-21 16:10:59.041220 DEBUG AppDaemon Section: None
2019-01-21 16:10:59.041336 DEBUG HADashboard Section: None

==> diag.log <==

==> error.log <==
```
