### ISSUE TITLE
Plugin Log Level

### ISSUE THREAD

**Issue by Odianosen25** [home-assistant/appdaemon#491]
Version AD 4.0

Plugin log level setting using `log_level` doesn't work

For example
```
MQTT:
      type: mqtt
      client_user: !secret mqtt_username
      client_password: !secret mqtt_password
      namespace: mqtt
      event_name: MQTT
      log_level: DEBUG
      client_topics:
          - presence/#
```

I get no log levels for that. It works for apps but not plugin.

Regards
