### ISSUE TITLE
500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by zacvoge** [home-assistant/appdaemon#493]
When i go to use this code i get the error 500
```
 title: Dorm
widget_dimensions: [125, 145]
widget_size: [1, 1]
widget_margins: [5, 10]
columns: 6
global_parameters:
    use_comma: 0
    precision: 1
    use_hass_icon: 1
away: 
    entity: script.1548212477606
    icon_on: mdi-home-lock
    icon_off: mdi-home-lock
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: red; font-size: 500%; margin-top: -10px;"
    title: Away
    title_style: "color: grey"
    widget_style: "background-color: black"
    widget_type: script
clock:
    date_style: "color: grey"
    time_style: "color: blue"
    widget_style: "background: black"
    widget_type: clock
fans_on: 
    entity: script.1548210809889
    icon_on: mdi-fan
    icon_off: mdi-fan
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: #3a4b82; font-size: 500%; margin-top: -10px;"
    title: Fans on
    title_style: "color: black"
    widget_style: "background-color:#191919 "
    widget_type: script
fans_off:
    entity: script.1548210857253
    icon_on: mdi-fan-off
    icon_off: mdi-fan-off
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: #424242; font-size: 500%; margin-top: -10px;"
    title: Fans off
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: script
google:
    entity: media_player.zacs_room_mini
    title: Google Home Speaker
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: media_player
home:
    entity: script.1548212099040
    icon_on: mdi-home-lock-open
    icon_off: mdi-home-lock-open
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: green; font-size: 500%; margin-top: -10px;"
    title: Home
    title_style: "color: grey"
    widget_style: "background-color: black"
    widget_type: script
lamp_on:
    entity: script.1548209227920
    icon_on: mdi-lightbulb-on
    icon_off: mdi-lightbulb-on
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: #726d25; font-size: 500%; margin-top: -10px;"
    title: Lamp on
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: script
lamp_off:
    entity: script.1548209299323
    icon_on: mdi-lightbulb-outline
    icon_off: mdi-lightbulb-outline
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: #424242; font-size: 500%; margin-top: -10px;"
    title: Lamp off
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: script
monitors_on:
    entity: script.1548211240181#67c6a3
    icon_on: mdi-monitor-dashboard
    icon_off: mdi-monitor-dashboard
    icon_style_inactive: "color: #67c6a3; font-size: 500%; margin-top: -10px;"
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    title: Monitors on
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: script
monitors_off:
    entity: script.1548211275949
    icon_on: mdi-monitor
    icon_off: mdi-monitor
    icon_style_inactive: "color: #39705c; font-size: 500%; margin-top: -10px;"
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    title: Monitors off
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: script
weather:
    title: Temperature
    entity: sensor.dark_sky_temperature
    widget_style: "background-color: black"
    title_style: "color: grey"
    
zac:
    title: Zac
    widget_type: device_tracker
    entity: device_tracker.zacks_iphone
    icon_on: fa-male
    icon_off: fa-male
    icon_style_active: "color: green; font-size: 450%; margin-top: -5px"
    icon_style_inactive: "color: red; font-size: 450%; margin-top: -5px"
    widget_style: "font-size: 125%"
    widget_style: "background-color: black"
    title_style: "color: grey"
    state_text_style: "color: grey; margin-top: -50px;"
3D_printers_on:
    entity: script.1548211117830
    icon_on: mdi-printer-3d
    icon_off: mdi-printer-3d
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: #f99602; font-size: 500%; margin-top: -10px;"
    title: 3D Printers on
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: script
3D_printers_off:
    entity: script.1548211163102
    icon_on: mdi-printer-3d
    icon_off: mdi-printer-3d
    icon_style_active: "color: black; font-size: 500%; margin-top: -10px;"
    icon_style_inactive: "color: #723b19; font-size: 500%; margin-top: -10px;"
    title: 3D Printers off
    title_style: "color: black"
    widget_style: "background-color: #191919"
    widget_type: script
layout:
    - clock(2x1), weather, zac, home, away
    - fans_on, lamp_on, monitors_on, 3D_printers_on, google(2x2)
    - fans_off, lamp_off, monitors_off, 3D_printers_off
```
