### ISSUE TITLE
Unexpected error when stopping appdaemon

### ISSUE THREAD

**Issue by foxy82** [home-assistant/appdaemon#523]
I get this error every time I stop AppDaemon

```
2019-02-19 09:38:48.224749 WARNING AppDaemon: ------------------------------------------------------------
2019-02-19 09:38:48.230536 WARNING AppDaemon: Unexpected error during state_update()
2019-02-19 09:38:48.235216 WARNING AppDaemon: ------------------------------------------------------------
2019-02-19 09:38:48.243144 WARNING AppDaemon: Traceback (most recent call last):
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 2349, in state_update
    self.process_event(namespace, data)
  File "/srv/appdaemon/lib/python3.5/site-packages/appdaemon/appdaemon.py", line 2380, in process_event
    if key in data["data"] and callback["kwargs"][key] != \
TypeError: argument of type 'NoneType' is not iterable

2019-02-19 09:38:48.248047 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by ReneTode** [comment]
what version from AD?
do you have apps running?
what kind of apps? how are they build?
how do you stop appdaemon?
what system are you running on?

its hard to say where such an error comes from without more information.

**Comment by foxy82** [comment]
Thanks for replying.

AD is 3.0.2.

I've got the MqttPlugin running. It is subscribing to a topic and when it gets a message it is running a bash script to use cecclient (on a Raspberry Pi Zero W).

Stopping appdaemon using systemd I used the service file provided for that.

Any more info I can give?

**Comment by foxy82** [comment]
Oh and the line just above the error is:
`AppDaemon: MQTT: Stoping MQTT Plugin and unsubscribing from URL hub:1883`

**Comment by ReneTode** [comment]
i think maybe the MQTT plugin gets an event after some parts are already closed.
i wouldnt worry about it.
the mqtt plugin has already changed much in the next version from AD, so its very well possible that this will disappear with the next release.

**Comment by foxy82** [comment]
The only thing is I think that might mean the message I'm trying to send in "terminate()" isn't being sent.

Essentially I'm trying to make it so that when the app is running then an mqtt switch in HA can get a status of online, and when I stop appdaemon it will go offline. I tried initially with the birth and will topics but maybe I'm not understanding how they work correctly.

Home Assistant config:

```
  - platform: mqtt
    name: "Studio TV"
    command_topic: "tv/studio/cmd"
    availability_topic: "tv/studio/LWT"

```


App Daemon config:

```
appdaemon:
  threads: 10
  longitude: 0
  latitude: 0
  elevation: 0
  app_dir: /home/appdaemon/.appdaemon/apps
  time_zone: Europe/London
  plugins:
    MQTT:
      type: mqtt
      client_host: hub
      client_port: 1883
      client_id: appdaemon_mqtt_client_pizerow2
      birth_topic: tv/studio/LWT
      will_topic: tv/studio/LWT
```
As that wasn't working I made init / terminate attempt to send a message for the availability - the init sends fine but the terminate doesn't when appdaemon is stopped. It sends ok when the app reloads due to a change in the app py file.

Any idea when the next version of the plugin will be out?

**Comment by Odianosen25** [comment]
@foxy82,

The `will_topic` is only used when the plugin disconnects from the broker in a non clean way; like AD stopping abruptly. If AD was stopped by the systemd as you said, the `will message` which is `offline` by default will not be sent as that is done cleanly. So your best bet, will be to use the `terminate` function to send a message when the the app is being stopped as that will happen when AD is stopped.

Are you sure your issue is not from another app? Have you tried removing the plugin, and see if you get the same problem? What other terminate functions do you have running?

Regards

**Comment by ReneTode** [comment]
@Odianosen25 if i read correct he has put in a send message in the terminate, and that causes the error.
so its worth to look into that, to see if a send message is correctly handled in terminate before the plugin is stopped.

@foxy82 the next release was planned almost 2 months ago, but real live has given that a curveball.
Andrew needs to clean up some more stuff before AD 4.0 beta is released, but real live keeps him a bit busy at the moment. we hope its released soon, but i cant give a timeframe.

**Comment by Odianosen25** [comment]
@ReneTode the reason I said so, was from the error he gave, its not from a message begin received, but a state update. There is no `state_update` in the MQTT plugin, so I don't think its from there.

@foxy82, can you kindly share the code that is being run in the terminate function?

Regards

**Comment by foxy82** [comment]
Hi,

So this app daemon has 3 apps running but two are "hello world" although I have just noticed they are extending the HASS plugin which I don't have installed.  Changing them to mqtt.Mqtt removes the error.

BUT...

The terminate method still doesn't fire. So here is the code of the app I'm running. 

```
import appdaemon.plugins.mqtt.mqttapi as mqtt
import subprocess

class CecTvMqtt(mqtt.Mqtt):

  def initialize(self):
    self.log("Starting TV MQTT CEC APP")
    self.listen_event(self.mqtt_message_recieved_event, topic= topic)
    self.mqtt_publish("tv/studio/LWT", "online", retain=True)

  def terminate(self):
    self.mqtt_publish("tv/studio/LWT", "offline", retain=True)

  def mqtt_message_recieved_event(self, event_name, data, kwargs):
    self.log("MQTT received {}".format(data))
    if data.get('payload') == 'ON':
      self.turn_on()
    else:
      self.turn_off()

  def turn_on(self):
    subprocess.check_output(['bash', '-c', "/tmp/turn_tv_on.sh"])

  def turn_off(self):
    subprocess.check_output(['bash', '-c', "/tmp/turn_tv_off.sh"])
```
and the app config:

```
tv_mqtt:
  module: tv_mqtt
  class: CecTvMqtt
```

and appdaemon config

```
log:
  logfile: /home/appdaemon/.appdaemon/log/appdaemon.log
  errorfile: /home/appdaemon/.appdaemon/log/appdaemon-error.log
  log_generations: 3
  log_size: 1000000

appdaemon:
  threads: 10
  longitude: 0
  latitude: 0
  elevation: 0
  app_dir: /home/appdaemon/.appdaemon/apps
  time_zone: Europe/London
  plugins:
    MQTT:
      type: mqtt
      client_host: hub
      client_port: 1883
      client_id: appdaemon_mqtt_client_pizerow2
      birth_topic: tv/studio/LWT
      will_topic: tv/studio/LWT
```
