### ISSUE TITLE
!secret being parsed out

### ISSUE THREAD

**Issue by kicker10BOG** [home-assistant/appdaemon#548]
I'm trying to setup AppDaemon for with HassOS and using a secret for the token like:
`token: !secret appdaemon_token`
but after restarting AppDaemon I check appdaemon.yaml and it has changed to:
`token: appdaemon_token`
It's as if `!secret` is being parsed out. 
Here is my file before it parses out the !secret:

```
secrets: /config/secrets.yaml
log:
  accessfile: /config/appdaemon/logs/access.log
  errorfile: /config/appdaemon/logs/error.log
  logfile: /config/appdaemon/logs/appdaemon.log
  log_generations: 3
  log_size: 1000000
appdaemon:
  threads: 10
  app_dir: /config/appdaemon/apps
  api_ssl_certificate: /ssl/fullchain.pem
  api_ssl_key: /ssl/privkey.pem
  plugins:
    HASS:
      type: hass
      ha_url: https://mysecrethass.com
      client_cert: /ssl/fullchain.pem
      cert_verify: true
      token: !secret appdaemon_token
hadashboard:
  dash_url: http://127.0.0.1:5050
  dash_dir: /config/appdaemon/dashboards
```
