### ISSUE TITLE
Priority issue - Apps not respecting priority 

### ISSUE THREAD

**Issue by ConnorGriffin** [home-assistant/appdaemon#561]
I am having an issue where my app priority doesn't seem to be respected. 

I have two apps, one that installs prerequisite python packages (install_dependencies), and one that imports one of those packages (cox_usage).

The apps are configured as follows:

```yaml
install_dependencies:
  module: install_deps
  class: InstallDeps
  priority: 0
  packages:
    - lxml
    - responses
    - mechanicalsoup

cox_usage:
  module: cox_usage
  class: CoxUsage
  priority: 99
```

Every time I recreate my docker container I have to comment out the cox_usage module, allow install_dependencies to complete, and then uncomment cox_usage. If i don't do this, AppDaemon gets stuck in a constant boot loop because cox_usage fails to load due to a ModuleNotFoundError. I have the exact same problem if I add install_dependencies as a dependency to the cox_usage app, so that's not a solution either. 

My understanding is that install_dependencies should run first, but it does not. 

I was able to remedy this in my testing by renaming install_dependencies to aaa_install_dependencies so that it runs first.
