### ISSUE TITLE
Google Calendar not triggering state change call-back

### ISSUE THREAD

**Issue by wasperen** [home-assistant/appdaemon#598]
Running latest versions.

I have a Google Calendar integration in Home Assistant. It has an entity_id of ```calendar.hass_calendar```. This entity correctly triggers a callback if I start listening to it.

The Google Calendar HA integration also has the ability to create separate "calendars", each with certain search terms. So, for instance, I have created a special calendar with entity_id ```calendar.cv_bathroom``` that shows up for any calendar entries that have the word "bathroom" in their title. Works well in HA. They show state in the HA developer utils.

But I noticed that these "synthetic" calendars do not get triggered in AD. Nothing happens there for these calendars -- only for the original ```calendar.hass_calendar```.

**Comment by Odianosen25** [comment]
Hello @wasperen,

that is weird as all entities should be trigger-able in AD. I have a similar setup, and it works fine for me. Could you possible share your code?

Regards

**Comment by wasperen** [comment]
Hey @Odianosen25 

You could have a look here: https://github.com/wasperen/climatecontrol/blob/per-zone-calendar/appdaemon/apps/climatecontrol.py

W

**Comment by ReneTode** [comment]
@wasperen  i got about 10 of those calendars myself, and they work fine.
```
- cal_id: some_id@group.calendar.google.com
  entities:
  - device_id: huisvuilkalender
    name: Huisvuilkalender
    track: true
  - device_id: bioton
    name: Biotonne
    track: true
    search: "#Biotonne"
  - device_id: wertstoff
    name: Wertstoftonne
    track: true
    search: "#Wertstofftonne"
  - device_id: hausmull
    name: Hausmulltonne
    track: true
    search: "#Hausmulltonne"
```
but i dont listen to attribute changes, but use on/off for trigger, so that might be it.

but i see a possible cause of a problem (you should check your error log)
```
		if "attributes" not in new_state or "message" not in new_state["attributes"]:
```
if attributes is not in new_state this will trow an error.
because the key attributes in new_state["attributes"] doesnt exist.
so split the if statement to something like:
```
message = "blablabla"
if "attributes" in new_state:
  if "message" in new_state["attributes"]:
    message = new_state["attributes"]["message"]
if message == "blablabla":
  self.log("Got a calendar state change with no message attribute: {}".format(new_state), level="WARNING")
```

but i did take a closer look at your code and you use on and off as point of action, so you dont need to all attrib changes.

i would use self.get_state(self.calendar,attribute="message") to get the message and just listen to the state changes.
