### ISSUE TITLE
502 Bad Gateway when proxifying the dashboard

### ISSUE THREAD

**Issue by wsw70** [home-assistant/appdaemon#643]
I am trying to proxify the dockerized AppDaemon dashboard. The following configuration (docker-compose) works fine:

```
  appdaemon:
      container_name: appdaemon
      image: acockburn/appdaemon:latest
      volumes:
        - /etc/docker/appdaemon:/conf
        - /etc/localtime:/etc/localtime:ro
      ports:
        - "5050:5050"
      restart: unless-stopped
      environment:
        - HA_URL=https://hass.mydomain
        - TOKEN=eyJ0e...
        - DASH_URL=http://appdaemon.mydomain:5050
```

This is the direct (not proxified) version which works via `http://appdaemon.mydomain:5050`.

I use `caddy` as a proxy to all my dockerized web services (about 20 of them), by turning the section above to

```
  appdaemon:
      container_name: appdaemon
      image: acockburn/appdaemon:latest
      volumes:
        - /etc/docker/appdaemon:/conf
        - /etc/localtime:/etc/localtime:ro
      restart: unless-stopped
      environment:
        - HA_URL=https://hass.mydomain
        - TOKEN=eyJ0e...
        - DASH_URL=http://appdaemon.mydomain
      labels:
         caddy.address: http://appdaemon.mydomain
         caddy.targetport: "5050"
```

In that case no ports are exposed and access to port `5050` of the container is done via the proxy managed by `caddy`. An alternative would be to use the popular `traefik` proxy.

With such a config I get a `502 Bad Gateway`  when connecting to `http://appdaemon.mydomain`. 

I suspect that the issue may be related to `DASH_URL`  and how it is interpreted internally (wild guessing here). What is the exact role of this variable?

EDIT: I had a look at how `caddy` proxifies the call and it dynamically builds the following configuration
```
http://appdaemon.mydomain {
  proxy / 172.21.0.36:5050 {
    transparent
  }
}
```

`172.21.0.36` is the current IP for the `appdaemon` container so maybe this clashes with `DASH_URL`? Since the IP will change I cannot fix that value.
