### ISSUE TITLE
RSS widget is not working

### ISSUE THREAD

**Issue by vkorn** [home-assistant/appdaemon#72]
Greetings, 

I'm using v2 and trying to add RSS widget to my dashboard. 
Even if everything is configured using examples, RSS is not displaying. 
AppDaemon config 
```yml
AppDaemon:
  cert_verify: False
  logfile: STDOUT
  errorfile: STDERR
  threads: 10
  app_dir: /config/hadaemon/apps
  rss_feeds: 
    - feed: http://rss.cnn.com/rss/cnn_topstories.rss
      target: cnn
  rss_update: 600
```

And in dashboard I have 
```yml
rss_cnn: 
  widget_type: rss
  title: CNN
  entity: cnn
  interval: 5
```

I couldn't find anything related to RSS in logs.
