### ISSUE TITLE
Device tracker icons not working in 2.0.0

### ISSUE THREAD

**Issue by duckpuppy** [home-assistant/appdaemon#76]
After upgrading from AppDaemon 2.0.0.beta3.5 to 2.0.0, my device tracker widgets are not showing icons, either by default or by setting `icon_on`/`icon_off`.  I've tried stopping AppDaemon, deleting the compiled directories, and restarting it to make sure that it's not issues with leftover cruft from the beta.

If I inspect the widgets in Chrome, I see that the icon gets rendered as `<i data-bind="attr: {class: icon}" class="False False"></i>`.  If I use the inspector to edit the class to "fa fa-male", things work.

**Comment by acockburn** [comment]
Can you post your dashboard file please?

**Comment by duckpuppy** [comment]
```yaml
#
# Main arguments
#
title: Test
widget_dimensions: [120, 120]
widget_size: [1, 1]
widget_margins: [5, 5]
columns: 8
global_parameters:
  use_comma: 0
  precision: 1
  use_hass_icon: 1

layout:
  - patrick_presence, renee_presence

patrick_presence:
  widget_type: device_tracker
  title: Patrick
  device: patrick_android

renee_presence:
  widget_type: device_tracker
  title: Renee
  device: renee_android
```
![presence](https://user-images.githubusercontent.com/19253/27929773-40ae9762-6262-11e7-84b3-f4d596e97869.png)
