### ISSUE TITLE
[REQUEST] Include example docker-compose file with Docker Tutorial

### ISSUE THREAD

**Issue by shbatm** [home-assistant/appdaemon#801]
Would like to propose including an example `docker-compose.yaml` file with the repo or in the Docker instructions in the `docs` folder.

Here's an example of one for using the latest beta version alongside a hassio installation:

```yaml
---
version: "3.7"

services:
  appdaemon:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: appdaemon
    image: acockburn/appdaemon:4.0.0b2
    hostname: appdaemon
    networks:
      - hassio
    ports:
      - "5050:5050"
    environment:
      HA_URL: http://hassio/homeassistant
      TOKEN: xxxxx-long_lived_access_token-xxxxx
      DASH_URL: http://hassio:5050
    volumes:
      - '/usr/share/hassio/homeassistant/appdaemon:/conf'
      - '/usr/share/hassio/homeassistant/secrets.yaml:/secrets.yaml:ro'
      - "/etc/localtime:/etc/localtime:ro"
      - "/usr/share/hassio/ssl:/certs:ro"
    restart: always

networks:
  hassio:
    external:
      name: hassio
```

**Comment by ReneTode** [comment]
i dont think many people will use hassio side by side with appdaemon in docker.
hassio has the AD addon.

so this example would not be really a good example.

**Comment by shbatm** [comment]
I was just using that example because that's what I had (the hassio add-on doesn't support v4 yet).

For a stand-alone HA docker install, it wouldn't be much different:
```yaml
---
version: "3.7"

services:
  appdaemon:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: appdaemon
    image: acockburn/appdaemon:4.0.0b2
    hostname: appdaemon
    ports:
      - "5050:5050"
    environment:
      HA_URL: http://<your_ha_url>/homeassistant
      TOKEN: xxxxx-long_lived_access_token-xxxxx
      DASH_URL: http://<your_ha_url>:5050
    volumes:
      - '${HOME}/.homeassistant/appdaemon:/conf'
      - '${HOME}/homeassistant/secrets.yaml:/secrets.yaml:ro'
      - "/etc/localtime:/etc/localtime:ro"
      - "./ssl:/certs:ro"
    restart: always
```

Just a thought to include since the docs already include the details for running via command line.

**Comment by ReneTode** [comment]
i know that the addon doesnt support AD 4 yet.
thats why almost no hassio users use AD 4 ;) 

the problem is that there is no default install. you can install HA on many different ways, on many different places. it doesnt even need to be on the same device.
if we provide an example in the docs, people will expect that we explain that example.
so it would need an explenation for things like ports, environment, volumes, etc.

and it would and up to be an example like:

```
version: "3.7" # or 3.6 or 3.8

services:
  appdaemon:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name:  anything  #give it a name
    image: acockburn/appdaemon:4.0.0b2
    hostname: appdaemon
    ports:
      - "xxxx:xxxx" # give an inner port number and an outer portnumber
    environment:
      HA_URL: http://<your_ha_url>
      TOKEN: xxxxx-long_lived_access_token-xxxxx
      DASH_URL: http://the_url_you_want_to_use
    volumes:
      - 'path/to/appdaemon/conf'
      - 'path/to/secrets.yaml:/secrets.yaml:ro' # if you would like to use another secrets.yaml then the default AD secrets.yaml, else delete this line
      - "/etc/localtime:/etc/localtime:ro"
      - "path/to/ssl:/certs:ro" # delete if you dont use ssl
    restart: always
```
i think the installation instruction in the documents work as they are, because we rarely get questions about them. an example like this would raise more questions then it answers, in my opinion.
