### ISSUE TITLE
4.0.3 Docker image unable to find modules

### ISSUE THREAD

**Issue by bmcgair** [home-assistant/appdaemon#924]
Trying to upgrade to the 4.0.3 docker image. All apps break with messages like:
```
2020-03-08 11:20:41.115068 WARNING AppDaemon: Unable to find module laundry - initialize() skipped
2020-03-08 11:20:41.115259 WARNING AppDaemon: Unable to find module shop - initialize() skipped
```
Conf dir mounted on /conf in the image. apps dir with apps.yaml and various apps (laundry.py, shop.py) in /conf/apps. Tried with both app_dir: /conf/apps set or unset. Same err.

appdaemon.yaml
```
#secrets: /config/secrets.yaml
logs:
  error_log:
    filename: /conf/errors.log
    log_generations: 1
  main_log:
    filename: /conf/appdaemon.log
    log_generations: 1
appdaemon:
  threads: 10
  app_dir: /conf/apps
  latitude: xx.xxxxxx
  longitude: -xxx.xxxxx
  elevation: 60
  time_zone: "us/pacific"
  plugins:
    HASS:
      type: hass
      ha_url: http://xxxx:8123
      token: xxx
hadashboard:
#  dash_url: http://127.0.0.1:5050
  dash_dir: /conf/dashboards
```
