### ISSUE TITLE
Rest not listening on port specified

### ISSUE THREAD

**Issue by landowark** [home-assistant/appdaemon#998]
I'm using version 4.0.3 non-Dockered and I'm trying to follow the instructions for RESTful API Support (https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#restful-api-support). However Appdaemon refuses to listen on the specified port.

According to a similar issue raised in (https://community.home-assistant.io/t/trouble-setting-up-api-endpoint/25916/5) the api can't listen on the same port as the dashboard, which is in conflict with the documentation. Okay, changed it to port 5000 in the config, but the results of "netstat -tulpn | grep 5000" are nil.

His problem seems to be related to his docker container not listening, but I'm not using docker.

My appdaemon.yaml file:
```yaml
appdaemon:
  threads: 10
  latitude: <somewhere>
  longitude: <somewhere>
  time_zone: <somewhere>
  elevation: 1
  plugins:
    HASS:
      type: hass
      ha_url: http://127.0.0.1:8123
      token: !secret appdaemontoken
  app_dir: /home/<user>/Scripts/appdaemon
  api_key: !secret adapikey
  api_port: 5000
logs:
  main_log:
    filename: /var/log/hass/appdaemon.log
  access_log:
    filename: /var/log/hass/ad-access.log
  error_log:
    filename: /var/log/hass/ad-error.log
api:
http:
  url: http://<local ip>:5050
  password: !secret ad_password
```

My test endpoint:
```python
import hassapi as hass

class ApiTest(hass.Hass):

    def initialize(self):
        self.register_endpoint(self.my_callback, "test_endpoint")
        self.log("Hello from ApiTest!")

    def my_callback(self, data):

        self.log(data)

        response = {"message": "Hello World"}

        return response, 200
```

Results of appdaemon.log on startup:

```log
2020-06-29 07:20:22.528940 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-06-29 07:20:22.532120 INFO AppDaemon: Initializing app api_test using class ApiTest from module apitest
2020-06-29 07:20:22.706243 INFO hello_world: Hello from AppDaemon
2020-06-29 07:20:22.707680 INFO hello_world: You are now ready to run Apps!
2020-06-29 07:20:22.711948 INFO api_test: Hello from ApiTest!
2020-06-29 07:20:22.714024 INFO AppDaemon: App initialization complete
```

I appreciate any suggestions.
